# ----------------SELLERS
GET http://localhost:3001/sellers
###

GET http://localhost:3001/sellers/1
###

POST http://localhost:3001/sellers
Content-Type: application/json

{
    "sellerName": "Lucas",
    "sellerPhone": "0432974"
}
###

DELETE http://localhost:3001/sellers/9
###

PATCH http://localhost:3001/sellers/1
Content-Type: application/json

{
    "name": "Lana",
    "phone": "584"
}
###

PATCH http://localhost:3001/sellers/Ana/3
###

# ----------------PRODUCTS
GET http://localhost:3001/products
###

GET http://localhost:3001/products/1
###

POST http://localhost:3001/sellers/1/products
Content-Type: application/json

{
    "category": "hat",
    "price": "22"
}

###

DELETE http://localhost:3001/products/20
###

PATCH http://localhost:3001/products/1
Content-Type: application/json

{
    "price": "30"
}
###

PATCH http://localhost:3001/products/2/price
Content-Type: application/json

{
    "price": "24"
}
###

# ---------------- ORDERS
GET http://localhost:3001/orders
###

GET http://localhost:3001/orders/2
###

POST http://localhost:3001/orders
###

# ---------------- ORDER ITEMS
GET http://localhost:3001/orderItems
###

GET http://localhost:3001/orderItems/1
###

POST http://localhost:3001/orders/2/orderItem/2
###

DELETE http://localhost:3001/orderItems/1
