# ----------------SELLERS
GET http://localhost:3001/sellers/all
###

GET http://localhost:3001/sellers/1
###

PUT http://localhost:3001/sellers/Fabian/9482904
###

DELETE http://localhost:3001/sellers/5
###

POST http://localhost:3001/sellers/057463298/2
###

PATCH http://localhost:3001/sellers/Ana/3
###

# ----------------PRODUCTS
GET http://localhost:3001/products/all
###

GET http://localhost:3001/products/2
###

PUT http://localhost:3001/sellers/2/products/t-shirt/20
###

DELETE http://localhost:3001/products/20
###

POST http://localhost:3001/products/2/scarf
###

PATCH http://localhost:3001/products/2/20
###

# ---------------- ORDERS
GET http://localhost:3001/orders/all
###

GET http://localhost:3001/orders/1
###

PUT http://localhost:3001/orders/4
###

# ---------------- ORDER ITEMS
GET http://localhost:3001/orderItems/all

